version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: /dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
    ports: 
      - 3306:3306
    networks:
      - authnetwork
  
  back:
    build: ./server
    ports: 
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - authnetwork
  react:
    build: ./client
    ports: 
      - 3000:3000
    networks:
      - authnetwork
networks:
  authnetwork: